contact_links:
  - name: Spec feedback ðŸ“ƒ
    url: https://github.com/FiloSottile/age/discussions/new?category=Spec-feedback
    about: Have a comment about the age spec as it's implemented by this and other tools?
  - name: UX report âœ¨
    url: https://github.com/FiloSottile/age/discussions/new?category=UX-reports
    about: Was age hard to use? It's not you, it's us. We want to hear about it.
